CREATE DATABASE IF NOT EXISTS mosyle DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE mosyle;

CREATE TABLE IF NOT EXISTS Users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    token CHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Drinks (
    id INT NOT NULL AUTO_INCREMENT,
    id_user INT NOT NULL,
    drink_ml INT NOT NULL,
    date_insert DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_drink
		FOREIGN KEY (id_user) REFERENCES Users (id) ON UPDATE CASCADE ON DELETE RESTRICT
);